"""set of functions and classes used in the context of networking and communication

Docs: https://vtecftwy.github.io/eccore/03_comms.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/0_03_comms.ipynb.

# %% ../nbs-dev/0_03_comms.ipynb #5bc6becf
from __future__ import annotations
from pathlib import Path

import os
import re

# %% auto #0
__all__ = ['CODE_ROOT', 'PACKAGE_ROOT', 'clean_no_proxy_12vpn']

# %% ../nbs-dev/0_03_comms.ipynb #fdd2f3f2
# Retrieve the package root
from . import __file__
CODE_ROOT = Path(__file__).parents[0]
PACKAGE_ROOT = Path(__file__).parents[1]

# %% ../nbs-dev/0_03_comms.ipynb #589b6fe8
def clean_no_proxy_12vpn():
    """Remove tokens like [fec0::], [fc00::], [fe80::]

    12VPN sets NO_PROXY to include tokens which causes problems with some libraries (e.g. openai, ...) that don't handle them correctly. 
    This function cleans the NO_PROXY environment variable by removing such tokens.
    """
    pattern = re.compile(r'^\[[^,\]]*::\*\]$')
    raw = os.environ.get("NO_PROXY") or os.environ.get("no_proxy") or ""
    items = [x.strip() for x in raw.split(",") if x.strip()]

    cleaned_items = [x for x in items if not pattern.match(x)]
    cleaned = ",".join(cleaned_items)

    os.environ["NO_PROXY"] = cleaned
    os.environ["no_proxy"] = cleaned
    return cleaned
